### ISSUE TITLE
Retrieving Dependencies on Windows with msvc

### ISSUE THREAD

**Issue by Nov0cx** [zaucy/bzlws#6]
MSVC doesn't understand command with a leading '-', there the comment have to start with a '/'. 
```bash
cl : Commandline warning D9002 : ignoring unknown option "-std=c++17".
The contents of <filesystem> are available only with C++17 or later.
external/bzlws/generators/cpp/cpp_generator.cc(10): 
```
<br/>
Maybe you can fix this with an option for windows.

**Comment by zaucy** [comment]
The select here isn't being hit in your configuration. https://github.com/zaucy/bzlws/blob/main/internal/copts.bzl#L6.

Are you using [bazels platforms](https://bazel.build/docs/platforms)? Most of my projects are using platforms and on windows using msvc I'm getting `/std:c++17`.

**Comment by Nov0cx** [comment]
Thank you. That fixes it.
